// Date: 22-Jul-13 15:59:17
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.arcticraft.model.item;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AC_ModelNPickaxe extends ModelBase
{

	//fields
	ModelRenderer Handle1;
	ModelRenderer Handle2;
	ModelRenderer Handle3;
	ModelRenderer Handle4;
	ModelRenderer Handle5;
	ModelRenderer Handle6;
	ModelRenderer Screw1;
	ModelRenderer Screw2;
	ModelRenderer Handle7;
	ModelRenderer Handle8;
	ModelRenderer Handle9;
	ModelRenderer Handle10;
	ModelRenderer Handle11;
	ModelRenderer Pick1;
	ModelRenderer Pick2;
	ModelRenderer Pick3;
	ModelRenderer Pick4;
	ModelRenderer Pick5;
	ModelRenderer Pick6;
	ModelRenderer Pick7;
	ModelRenderer Pick8;
	ModelRenderer Pick9;

	public AC_ModelNPickaxe()
	{
		textureWidth = 64;
		textureHeight = 64;

		Handle1 = new ModelRenderer(this, 0, 0);
		Handle1.addBox(0F, 0F, 0F, 2, 21, 2);
		Handle1.setRotationPoint(- 1F, 3F, - 1F);
		Handle1.setTextureSize(64, 64);
		Handle1.mirror = true;
		setRotation(Handle1, 0F, 0F, 0F);
		Handle2 = new ModelRenderer(this, 0, 25);
		Handle2.addBox(0F, 0F, 0F, 4, 6, 4);
		Handle2.setRotationPoint(- 2F, - 3F, - 2F);
		Handle2.setTextureSize(64, 64);
		Handle2.mirror = true;
		setRotation(Handle2, 0F, 0F, 0F);
		Handle3 = new ModelRenderer(this, 0, 39);
		Handle3.addBox(0F, 0F, 0F, 2, 2, 1);
		Handle3.setRotationPoint(- 1F, 3F, - 2F);
		Handle3.setTextureSize(64, 64);
		Handle3.mirror = true;
		setRotation(Handle3, 1.003822F, 0F, 0F);
		Handle4 = new ModelRenderer(this, 0, 39);
		Handle4.addBox(0F, 0F, 0F, 1, 2, 2);
		Handle4.setRotationPoint(1F, 2F, - 1F);
		Handle4.setTextureSize(64, 64);
		Handle4.mirror = true;
		setRotation(Handle4, 0F, 0F, 0.7063936F);
		Handle5 = new ModelRenderer(this, 0, 39);
		Handle5.addBox(0F, 0F, 0F, 1, 2, 2);
		Handle5.setRotationPoint(- 2F, 2.4F, - 1F);
		Handle5.setTextureSize(64, 64);
		Handle5.mirror = true;
		setRotation(Handle5, 0F, 0F, - 0.7063936F);
		Handle6 = new ModelRenderer(this, 0, 39);
		Handle6.addBox(0F, 0F, 0F, 2, 2, 1);
		Handle6.setRotationPoint(- 1F, 2.2F, 1.4F);
		Handle6.setTextureSize(64, 64);
		Handle6.mirror = true;
		setRotation(Handle6, - 1.003822F, 0F, 0F);
		Screw1 = new ModelRenderer(this, 0, 45);
		Screw1.addBox(0F, - 4F, 0F, 2, 1, 2);
		Screw1.setRotationPoint(- 1F, 0F, - 1F);
		Screw1.setTextureSize(64, 64);
		Screw1.mirror = true;
		setRotation(Screw1, 0F, 0F, 0F);
		Screw2 = new ModelRenderer(this, 0, 45);
		Screw2.addBox(0F, 0F, 0F, 2, 1, 2);
		Screw2.setRotationPoint(0F, - 4F, - 1.5F);
		Screw2.setTextureSize(64, 64);
		Screw2.mirror = true;
		setRotation(Screw2, 0F, - 0.8551081F, 0F);
		Handle7 = new ModelRenderer(this, 25, 0);
		Handle7.addBox(0F, 0F, 0F, 4, 1, 4);
		Handle7.setRotationPoint(- 2F, 21F, - 2F);
		Handle7.setTextureSize(64, 64);
		Handle7.mirror = true;
		setRotation(Handle7, 0F, 0F, 0F);
		Handle8 = new ModelRenderer(this, 27, 7);
		Handle8.addBox(0F, 0F, 0F, 3, 5, 3);
		Handle8.setRotationPoint(- 1.5F, 16F, - 1.5F);
		Handle8.setTextureSize(64, 64);
		Handle8.mirror = true;
		setRotation(Handle8, 0F, 0F, 0F);
		Handle9 = new ModelRenderer(this, 25, 0);
		Handle9.addBox(0F, 0F, 0F, 4, 1, 4);
		Handle9.setRotationPoint(- 2F, 15F, - 2F);
		Handle9.setTextureSize(64, 64);
		Handle9.mirror = true;
		setRotation(Handle9, 0F, 0F, 0F);
		Handle10 = new ModelRenderer(this, 27, 17);
		Handle10.addBox(0F, 0F, 0F, 3, 1, 3);
		Handle10.setRotationPoint(- 1.5F, 14.6F, - 1.5F);
		Handle10.setTextureSize(64, 64);
		Handle10.mirror = true;
		setRotation(Handle10, 0F, 0F, 0F);
		Handle11 = new ModelRenderer(this, 27, 17);
		Handle11.addBox(0F, 0F, 0F, 3, 1, 3);
		Handle11.setRotationPoint(- 1.5F, 21.4F, - 1.5F);
		Handle11.setTextureSize(64, 64);
		Handle11.mirror = true;
		setRotation(Handle11, 0F, 0F, 0F);
		Pick1 = new ModelRenderer(this, 22, 23);
		Pick1.addBox(0F, 0F, 0F, 8, 3, 3);
		Pick1.setRotationPoint(- 4F, - 2.4F, - 1.5F);
		Pick1.setTextureSize(64, 64);
		Pick1.mirror = true;
		setRotation(Pick1, 0F, 0F, 0F);
		Pick2 = new ModelRenderer(this, 27, 31);
		Pick2.addBox(0F, 0F, 0F, 3, 4, 3);
		Pick2.setRotationPoint(4F, - 3.2F, - 1.5F);
		Pick2.setTextureSize(64, 64);
		Pick2.mirror = true;
		setRotation(Pick2, 0F, 0F, 0F);
		Pick3 = new ModelRenderer(this, 27, 31);
		Pick3.addBox(0F, 0F, 0F, 3, 4, 3);
		Pick3.setRotationPoint(- 7F, - 3.2F, - 1.5F);
		Pick3.setTextureSize(64, 64);
		Pick3.mirror = true;
		setRotation(Pick3, 0F, 0F, 0F);
		Pick4 = new ModelRenderer(this, 26, 40);
		Pick4.addBox(0F, 0F, 0F, 5, 2, 2);
		Pick4.setRotationPoint(7F, - 2.7F, - 1F);
		Pick4.setTextureSize(64, 64);
		Pick4.mirror = true;
		setRotation(Pick4, 0F, 0F, 0.1858931F);
		Pick5 = new ModelRenderer(this, 26, 40);
		Pick5.addBox(0F, 0F, 0F, 5, 2, 2);
		Pick5.setRotationPoint(- 12F, - 2F, - 1F);
		Pick5.setTextureSize(64, 64);
		Pick5.mirror = true;
		setRotation(Pick5, 0F, 0F, - 0.1487144F);
		Pick6 = new ModelRenderer(this, 28, 46);
		Pick6.addBox(0F, 0F, 0F, 3, 1, 2);
		Pick6.setRotationPoint(11.7F, - 1.5F, - 1F);
		Pick6.setTextureSize(64, 64);
		Pick6.mirror = true;
		setRotation(Pick6, 0F, 0F, 0.2974289F);
		Pick7 = new ModelRenderer(this, 28, 46);
		Pick7.addBox(0F, 0F, 0F, 3, 1, 2);
		Pick7.setRotationPoint(- 14.8F, - 0.8F, - 1F);
		Pick7.setTextureSize(64, 64);
		Pick7.mirror = true;
		setRotation(Pick7, 0F, 0F, - 0.2974289F);
		Pick8 = new ModelRenderer(this, 29, 51);
		Pick8.addBox(0F, 0F, 0F, 2, 0, 2);
		Pick8.setRotationPoint(14F, - 0.4F, - 1F);
		Pick8.setTextureSize(64, 64);
		Pick8.mirror = true;
		setRotation(Pick8, 0F, 0F, 0.4461433F);
		Pick9 = new ModelRenderer(this, 29, 51);
		Pick9.addBox(0F, 0F, 0F, 2, 0, 2);
		Pick9.setRotationPoint(- 16F, 0.3F, - 1F);
		Pick9.setTextureSize(64, 64);
		Pick9.mirror = true;
		setRotation(Pick9, 0F, 0F, - 0.4461433F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Handle1.render(f5);
		Handle2.render(f5);
		Handle3.render(f5);
		Handle4.render(f5);
		Handle5.render(f5);
		Handle6.render(f5);
		Screw1.render(f5);
		Screw2.render(f5);
		Handle7.render(f5);
		Handle8.render(f5);
		Handle9.render(f5);
		Handle10.render(f5);
		Handle11.render(f5);
		Pick1.render(f5);
		Pick2.render(f5);
		Pick3.render(f5);
		Pick4.render(f5);
		Pick5.render(f5);
		Pick6.render(f5);
		Pick7.render(f5);
		Pick8.render(f5);
		Pick9.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par6Entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, par6Entity);
	}

}
