// Date: 09-Aug-13 13:41:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package arcticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AC_ModelClub extends ModelBase
{
  //fields
    ModelRenderer C1;
    ModelRenderer C2;
    ModelRenderer C3;
    ModelRenderer C4;
    ModelRenderer C5;
    ModelRenderer C6;
    ModelRenderer C7;
    ModelRenderer C8;
    ModelRenderer C9;
    ModelRenderer C10;
    ModelRenderer C11;
    ModelRenderer C12;
    ModelRenderer C13;
    ModelRenderer C14;
    ModelRenderer C15;
    ModelRenderer C16;
    ModelRenderer C17;
    ModelRenderer C18;
    ModelRenderer C19;
    ModelRenderer C20;
    ModelRenderer C21;
    ModelRenderer C22;
    ModelRenderer C23;
  
  public AC_ModelClub()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      C1 = new ModelRenderer(this, 0, 0);
      C1.addBox(0F, 0F, 0F, 8, 1, 8);
      C1.setRotationPoint(-4F, 1F, -4F);
      C1.setTextureSize(64, 64);
      C1.mirror = true;
      setRotation(C1, 0F, 0F, 0F);
      C2 = new ModelRenderer(this, 0, 0);
      C2.addBox(0F, 0F, 0F, 6, 7, 6);
      C2.setRotationPoint(-3F, 2F, -3F);
      C2.setTextureSize(64, 64);
      C2.mirror = true;
      setRotation(C2, 0F, 0F, 0F);
      C3 = new ModelRenderer(this, 0, 0);
      C3.addBox(0F, 0F, 0F, 4, 10, 5);
      C3.setRotationPoint(-2F, 9F, -2.5F);
      C3.setTextureSize(64, 64);
      C3.mirror = true;
      setRotation(C3, 0F, 0F, 0F);
      C4 = new ModelRenderer(this, 0, 0);
      C4.addBox(0F, 0F, 0F, 3, 5, 3);
      C4.setRotationPoint(-1.5F, 19F, -1.5F);
      C4.setTextureSize(64, 64);
      C4.mirror = true;
      setRotation(C4, 0F, 0F, 0F);
      C5 = new ModelRenderer(this, 0, 0);
      C5.addBox(0F, 0F, 0F, 10, 1, 10);
      C5.setRotationPoint(-5F, 0F, -5F);
      C5.setTextureSize(64, 64);
      C5.mirror = true;
      setRotation(C5, 0F, 0F, 0F);
      C6 = new ModelRenderer(this, 0, 0);
      C6.addBox(0F, 0F, 0F, 12, 1, 12);
      C6.setRotationPoint(-6F, -1F, -6F);
      C6.setTextureSize(64, 64);
      C6.mirror = true;
      setRotation(C6, 0F, 0F, 0F);
      C7 = new ModelRenderer(this, 0, 0);
      C7.addBox(0F, 0F, 0F, 14, 15, 14);
      C7.setRotationPoint(-7F, -16F, -7F);
      C7.setTextureSize(64, 64);
      C7.mirror = true;
      setRotation(C7, 0F, 0F, 0F);
      C8 = new ModelRenderer(this, 0, 0);
      C8.addBox(0F, 0F, 0F, 15, 9, 8);
      C8.setRotationPoint(-7.5F, -13F, -4F);
      C8.setTextureSize(64, 64);
      C8.mirror = true;
      setRotation(C8, 0F, 0F, 0F);
      C9 = new ModelRenderer(this, 0, 0);
      C9.addBox(0F, 0F, 0F, 15, 1, 6);
      C9.setRotationPoint(-7.5F, -4F, -3F);
      C9.setTextureSize(64, 64);
      C9.mirror = true;
      setRotation(C9, 0F, 0F, 0F);
      C10 = new ModelRenderer(this, 0, 0);
      C10.addBox(0F, 0F, 0F, 15, 1, 6);
      C10.setRotationPoint(-7.5F, -14F, -3F);
      C10.setTextureSize(64, 64);
      C10.mirror = true;
      setRotation(C10, 0F, 0F, 0F);
      C11 = new ModelRenderer(this, 0, 0);
      C11.addBox(0F, 0F, 0F, 15, 7, 1);
      C11.setRotationPoint(-7.5F, -12F, 4F);
      C11.setTextureSize(64, 64);
      C11.mirror = true;
      setRotation(C11, 0F, 0F, 0F);
      C12 = new ModelRenderer(this, 0, 0);
      C12.addBox(0F, 0F, 0F, 15, 7, 1);
      C12.setRotationPoint(-7.5F, -12F, -5F);
      C12.setTextureSize(64, 64);
      C12.mirror = true;
      setRotation(C12, 0F, 0F, 0F);
      C13 = new ModelRenderer(this, 0, 0);
      C13.addBox(0F, 0F, 0F, 8, 9, 15);
      C13.setRotationPoint(-4F, -13F, -7.5F);
      C13.setTextureSize(64, 64);
      C13.mirror = true;
      setRotation(C13, 0F, 0F, 0F);
      C14 = new ModelRenderer(this, 0, 0);
      C14.addBox(0F, 0F, 0F, 1, 7, 15);
      C14.setRotationPoint(-5F, -12F, -7.5F);
      C14.setTextureSize(64, 64);
      C14.mirror = true;
      setRotation(C14, 0F, 0F, 0F);
      C15 = new ModelRenderer(this, 0, 0);
      C15.addBox(0F, 0F, 0F, 1, 7, 15);
      C15.setRotationPoint(4F, -12F, -7.5F);
      C15.setTextureSize(64, 64);
      C15.mirror = true;
      setRotation(C15, 0F, 0F, 0F);
      C16 = new ModelRenderer(this, 0, 0);
      C16.addBox(0F, 0F, 0F, 6, 1, 15);
      C16.setRotationPoint(-3F, -4F, -7.5F);
      C16.setTextureSize(64, 64);
      C16.mirror = true;
      setRotation(C16, 0F, 0F, 0F);
      C17 = new ModelRenderer(this, 0, 0);
      C17.addBox(0F, 0F, 0F, 6, 1, 15);
      C17.setRotationPoint(-3F, -14F, -7.5F);
      C17.setTextureSize(64, 64);
      C17.mirror = true;
      setRotation(C17, 0F, 0F, 0F);
      C18 = new ModelRenderer(this, 0, 0);
      C18.addBox(0F, 0F, 0F, 12, 2, 12);
      C18.setRotationPoint(-6F, -18F, -5.866667F);
      C18.setTextureSize(64, 64);
      C18.mirror = true;
      setRotation(C18, 0F, 0F, 0F);
      C19 = new ModelRenderer(this, 0, 0);
      C19.addBox(0F, 0F, 0F, 8, 1, 8);
      C19.setRotationPoint(-4F, -18.5F, -4F);
      C19.setTextureSize(64, 64);
      C19.mirror = true;
      setRotation(C19, 0F, 0F, 0F);
      C20 = new ModelRenderer(this, 0, 0);
      C20.addBox(0F, 0F, 0F, 6, 1, 1);
      C20.setRotationPoint(-3F, -18.5F, 4F);
      C20.setTextureSize(64, 64);
      C20.mirror = true;
      setRotation(C20, 0F, 0F, 0F);
      C21 = new ModelRenderer(this, 0, 0);
      C21.addBox(0F, 0F, 0F, 6, 1, 1);
      C21.setRotationPoint(-3F, -18.5F, -5F);
      C21.setTextureSize(64, 64);
      C21.mirror = true;
      setRotation(C21, 0F, 0F, 0F);
      C22 = new ModelRenderer(this, 0, 0);
      C22.addBox(0F, 0F, 0F, 1, 1, 6);
      C22.setRotationPoint(-5F, -18.5F, -3F);
      C22.setTextureSize(64, 64);
      C22.mirror = true;
      setRotation(C22, 0F, 0F, 0F);
      C23 = new ModelRenderer(this, 0, 0);
      C23.addBox(0F, 0F, 0F, 1, 1, 6);
      C23.setRotationPoint(4F, -18.5F, -3F);
      C23.setTextureSize(64, 64);
      C23.mirror = true;
      setRotation(C23, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    C1.render(f5);
    C2.render(f5);
    C3.render(f5);
    C4.render(f5);
    C5.render(f5);
    C6.render(f5);
    C7.render(f5);
    C8.render(f5);
    C9.render(f5);
    C10.render(f5);
    C11.render(f5);
    C12.render(f5);
    C13.render(f5);
    C14.render(f5);
    C15.render(f5);
    C16.render(f5);
    C17.render(f5);
    C18.render(f5);
    C19.render(f5);
    C20.render(f5);
    C21.render(f5);
    C22.render(f5);
    C23.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par6Entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, par6Entity);
  }

}
