// Date: 25-May-13 14:46:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package arcticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AC_ModelPlainStatue extends ModelBase
{

	//fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer PedestalInside;
	ModelRenderer PedestalBase;
	ModelRenderer PedestalMid;
	ModelRenderer PedestalTop;
	ModelRenderer Side;
	ModelRenderer Side1;
	ModelRenderer Side2;
	ModelRenderer Side3;
	ModelRenderer Side4;
	ModelRenderer Side5;
	ModelRenderer Side6;
	ModelRenderer Side7;
	ModelRenderer Side8;
	ModelRenderer Side9;
	ModelRenderer Side10;
	ModelRenderer Side11;

	public AC_ModelPlainStatue()
	{
		textureWidth = 64;
		textureHeight = 64;

		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, -8F, 0F);
		head.setTextureSize(64, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 16, 16);
		body.addBox(-4F, 0F, -2F, 8, 12, 4);
		body.setRotationPoint(0F, -8F, 0F);
		body.setTextureSize(64, 64);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		rightarm = new ModelRenderer(this, 40, 16);
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
		rightarm.setRotationPoint(-5F, -6F, 0F);
		rightarm.setTextureSize(64, 64);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0.0743572F, 0.0743572F);
		leftarm = new ModelRenderer(this, 40, 16);
		leftarm.addBox(-1F, -2F, -1.8F, 4, 12, 4);
		leftarm.setRotationPoint(5F, -5F, -1F);
		leftarm.setTextureSize(64, 64);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0.4833219F, -1.784573F);
		rightleg = new ModelRenderer(this, 0, 16);
		rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		rightleg.setRotationPoint(-2F, 4F, 0F);
		rightleg.setTextureSize(64, 64);
		rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		leftleg = new ModelRenderer(this, 0, 16);
		leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		leftleg.setRotationPoint(2F, 4F, 0F);
		leftleg.setTextureSize(64, 64);
		leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
		PedestalInside = new ModelRenderer(this, 0, 0);
		PedestalInside.addBox(0F, 0F, 0F, 1, 1, 1);
		PedestalInside.setRotationPoint(0F, 0F, 0F);
		PedestalInside.setTextureSize(64, 64);
		PedestalInside.mirror = true;
		setRotation(PedestalInside, 0F, 0F, 0F);
		PedestalBase = new ModelRenderer(this, -2, 39);
		PedestalBase.addBox(0F, 0F, 0F, 16, 1, 16);
		PedestalBase.setRotationPoint(-8F, 23F, -8F);
		PedestalBase.setTextureSize(64, 64);
		PedestalBase.mirror = true;
		setRotation(PedestalBase, 0F, 0F, 0F);
		PedestalMid = new ModelRenderer(this, 32, 0);
		PedestalMid.addBox(0F, 0F, 0F, 14, 1, 14);
		PedestalMid.setRotationPoint(-7F, 22F, -7F);
		PedestalMid.setTextureSize(64, 64);
		PedestalMid.mirror = true;
		setRotation(PedestalMid, 0F, 0F, 0F);
		PedestalTop = new ModelRenderer(this, 12, 40);
		PedestalTop.addBox(0F, 0F, 0F, 12, 1, 12);
		PedestalTop.setRotationPoint(-6F, 16F, -6F);
		PedestalTop.setTextureSize(64, 64);
		PedestalTop.mirror = true;
		setRotation(PedestalTop, 0F, 0F, 0F);
		Side = new ModelRenderer(this, 0, 0);
		Side.addBox(0F, 0F, 0F, 4, 5, 1);
		Side.setRotationPoint(3F, 17F, -7F);
		Side.setTextureSize(64, 64);
		Side.mirror = true;
		setRotation(Side, 0F, 0F, 0F);
		Side1 = new ModelRenderer(this, 0, 0);
		Side1.addBox(0F, 0F, 0F, 6, 5, 1);
		Side1.setRotationPoint(6F, 17F, -3F);
		Side1.setTextureSize(64, 64);
		Side1.mirror = true;
		setRotation(Side1, 0F, -1.570796F, 0F);
		Side2 = new ModelRenderer(this, 0, 0);
		Side2.addBox(0F, 0F, 0F, 6, 5, 1);
		Side2.setRotationPoint(-3F, 17F, -6F);
		Side2.setTextureSize(64, 64);
		Side2.mirror = true;
		setRotation(Side2, 0F, 0F, 0F);
		Side3 = new ModelRenderer(this, 0, 0);
		Side3.addBox(0F, 0F, 0F, 4, 5, 1);
		Side3.setRotationPoint(-7F, 17F, -7F);
		Side3.setTextureSize(64, 64);
		Side3.mirror = true;
		setRotation(Side3, 0F, 0F, 0F);
		Side4 = new ModelRenderer(this, 23, 39);
		Side4.addBox(0F, 0F, 0F, 4, 5, 1);
		Side4.setRotationPoint(-7F, 17F, 7F);
		Side4.setTextureSize(64, 64);
		Side4.mirror = true;
		setRotation(Side4, 0F, 1.570796F, 0F);
		Side5 = new ModelRenderer(this, 41, 0);
		Side5.addBox(0F, 0F, 0F, 4, 5, 1);
		Side5.setRotationPoint(6F, 17F, -3F);
		Side5.setTextureSize(64, 64);
		Side5.mirror = true;
		setRotation(Side5, 0F, 1.570796F, 0F);
		Side6 = new ModelRenderer(this, 41, 0);
		Side6.addBox(0F, 0F, 0F, 4, 5, 1);
		Side6.setRotationPoint(-7F, 17F, 6F);
		Side6.setTextureSize(64, 64);
		Side6.mirror = true;
		setRotation(Side6, 0F, 0F, 0F);
		Side7 = new ModelRenderer(this, 42, 0);
		Side7.addBox(0F, 0F, 0F, 6, 5, 1);
		Side7.setRotationPoint(-3F, 17F, 5F);
		Side7.setTextureSize(64, 64);
		Side7.mirror = true;
		setRotation(Side7, 0F, 0F, 0F);
		Side8 = new ModelRenderer(this, 23, 0);
		Side8.addBox(0F, 0F, 0F, 6, 5, 1);
		Side8.setRotationPoint(-5F, 17F, -3F);
		Side8.setTextureSize(64, 64);
		Side8.mirror = true;
		setRotation(Side8, 0F, -1.570796F, 0F);
		Side9 = new ModelRenderer(this, 0, 0);
		Side9.addBox(0F, 0F, 0F, 4, 5, 1);
		Side9.setRotationPoint(-7F, 17F, -3F);
		Side9.setTextureSize(64, 64);
		Side9.mirror = true;
		setRotation(Side9, 0F, 1.570796F, 0F);
		Side10 = new ModelRenderer(this, 41, 0);
		Side10.addBox(0F, 0F, 0F, 4, 5, 1);
		Side10.setRotationPoint(3F, 17F, 6F);
		Side10.setTextureSize(64, 64);
		Side10.mirror = true;
		setRotation(Side10, 0F, 0F, 0F);
		Side11 = new ModelRenderer(this, 41, 0);
		Side11.addBox(0F, 0F, 0F, 4, 5, 1);
		Side11.setRotationPoint(6F, 17F, 7F);
		Side11.setTextureSize(64, 64);
		Side11.mirror = true;
		setRotation(Side11, 0F, 1.570796F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		head.render(f5);
		body.render(f5);
		rightarm.render(f5);
		leftarm.render(f5);
		rightleg.render(f5);
		leftleg.render(f5);
		PedestalInside.render(f5);
		PedestalBase.render(f5);
		PedestalMid.render(f5);
		PedestalTop.render(f5);
		Side.render(f5);
		Side1.render(f5);
		Side2.render(f5);
		Side3.render(f5);
		Side4.render(f5);
		Side5.render(f5);
		Side6.render(f5);
		Side7.render(f5);
		Side8.render(f5);
		Side9.render(f5);
		Side10.render(f5);
		Side11.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par6Entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, par6Entity);
	}

	public void renderAll()
	{
		head.render(0.0625F);
		body.render(0.0625F);
		rightarm.render(0.0625F);
		leftarm.render(0.0625F);
		rightleg.render(0.0625F);
		leftleg.render(0.0625F);
		PedestalInside.render(0.0625F);
		PedestalBase.render(0.0625F);
		PedestalMid.render(0.0625F);
		PedestalTop.render(0.0625F);
		Side.render(0.0625F);
		Side1.render(0.0625F);
		Side2.render(0.0625F);
		Side3.render(0.0625F);
		Side4.render(0.0625F);
		Side5.render(0.0625F);
		Side6.render(0.0625F);
		Side7.render(0.0625F);
		Side8.render(0.0625F);
		Side9.render(0.0625F);
		Side10.render(0.0625F);
		Side11.render(0.0625F);
	}

}
