// Date: 17/06/2013 21:36:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package arcticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AC_ModelFrostGhost extends ModelBase
{
  //fields
    ModelRenderer hood;
    ModelRenderer backtail;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer body;
    ModelRenderer head;
    ModelRenderer hood1;
    ModelRenderer hood2;
    ModelRenderer hood3;
    ModelRenderer hood_4;
    ModelRenderer Tail;
  
  public AC_ModelFrostGhost()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      hood = new ModelRenderer(this, 0, 15);
      hood.addBox(0F, 0F, 0F, 7, 1, 1);
      hood.setRotationPoint(-3F, -7F, -5F);
      hood.setTextureSize(64, 64);
      hood.mirror = true;
      setRotation(hood, 0F, 0F, 1.570796F);
      backtail = new ModelRenderer(this, 48, 0);
      backtail.addBox(-4F, -4F, 0F, 4, 9, 2);
      backtail.setRotationPoint(3F, 19F, 5F);
      backtail.setTextureSize(64, 64);
      backtail.mirror = true;
      setRotation(backtail, 0.6981317F, -0.3490659F, 0.0872665F);
      rightarm = new ModelRenderer(this, 30, 27);
      rightarm.addBox(-2F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 1.48353F, -2.879793F, 0.0872665F);
      leftarm = new ModelRenderer(this, 30, 27);
      leftarm.mirror = true;
      leftarm.addBox(-2F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 1.570796F, 2.96706F, -0.0872665F);
      leftarm.mirror = false;
      body = new ModelRenderer(this, 30, 11);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, -0.0523599F, 3.141593F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(0F, 0F, 0F, 8, 8, 7);
      head.setRotationPoint(-4F, -8F, -4F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      hood1 = new ModelRenderer(this, 0, 17);
      hood1.addBox(-4F, -8F, -4F, 1, 1, 1);
      hood1.setRotationPoint(6F, 1F, -1F);
      hood1.setTextureSize(64, 64);
      hood1.mirror = true;
      setRotation(hood1, 0F, 0F, 0F);
      hood2 = new ModelRenderer(this, 0, 15);
      hood2.addBox(-4F, -8F, -4F, 7, 1, 1);
      hood2.setRotationPoint(-4F, -3F, -1F);
      hood2.setTextureSize(64, 64);
      hood2.mirror = true;
      setRotation(hood2, 0F, 0F, 1.570796F);
      hood3 = new ModelRenderer(this, 0, 15);
      hood3.addBox(-4F, -8F, -4F, 8, 1, 1);
      hood3.setRotationPoint(0F, 0F, -1F);
      hood3.setTextureSize(64, 64);
      hood3.mirror = true;
      setRotation(hood3, 0F, 0F, 0F);
      hood_4 = new ModelRenderer(this, 0, 17);
      hood_4.addBox(-4F, -8F, -4F, 1, 1, 1);
      hood_4.setRotationPoint(1F, 1F, -1F);
      hood_4.setTextureSize(64, 64);
      hood_4.mirror = true;
      setRotation(hood_4, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 30, 0);
      Tail.addBox(-4F, -4F, 1F, 6, 8, 3);
      Tail.setRotationPoint(2F, 15F, 0F);
      Tail.setTextureSize(64, 64);
      Tail.mirror = true;
      setRotation(Tail, 0.5235988F, 0F, -0.1745329F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    hood.render(par7);
    backtail.render(par7);
    rightarm.render(par7);
    leftarm.render(par7);
    body.render(par7);
    head.render(par7);
    hood1.render(par7);
    hood2.render(par7);
    hood3.render(par7);
    hood_4.render(par7);
    Tail.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
